export const SELECTED_EXTERIOR_COLOUR = "SELECTED_EXTERIOR_COLOUR";
export const SELECTED_INTERIOR_COLOUR = "SELECTED_INTERIOR_COLOUR";
export const SELECTED_WHEEL_TYPE = "SELECTED_WHEEL_TYPE";
export const SELECTED_FULL_SELF_DRIVING = "SELECTED_FULL_SELF_DRIVING";
export const SELECTED_PERFORMANCE_PACKAGE = "SELECTED_PERFORMANCE_PACKAGE";
export const SELECTED_CENTER_CONSOLE_TRAYS = "SELECTED_CENTER_CONSOLE_TRAYS";
export const SELECTED_SUNSHADE = "SELECTED_SUNSHADE";
export const SELECTED_ALL_WEATHER_INTERIOR_LINERS =
  "SELECTED_ALL_WEATHER_INTERIOR_LINERS";
export const UPDATE_DOWN_PAYMENT = "UPDATE_DOWN_PAYMENT";
export const UPDATE_MONTHLY_PAYMENT = "UPDATE_MONTHLY_PAYMENT";
export const UPDATE_LOAN_AMOUNT = "UPDATE_LOAN_AMOUNT";
export const UPDATE_TIME = "UPDATE_TIME";
